### PR TITLE
Revert "fix filename calculation"

### PR DESCRIPTION
**Pull request by martinklepsch**
This reverts commit 1486803407a425f7b627161971686823753c94e9.

### CODE REVIEW

**Comment by podviaznikov** [comment]
Ahh, I tested this with 1 example site and 1 real site and still broke it. Let me quickly test this revert to see  if it breaks something else

**Comment by podviaznikov** [comment]
Everything works fine. Now I'm confused why I did that change. I don't see code that relies on it.

**Comment by podviaznikov** [comment]
thanks for fixing! @martinklepsch :+1:

**Comment by martinklepsch** [comment]
Perfect. Thanks! :)

**Pull request merged**
