### PR TITLE
Default to https for gravatar links

### PR DESCRIPTION
**Pull request by arichiardi**
It was old-style http and we want to default to https instead.

This also introduces the new `boot test` task with the right setup for
reporting and exiting correctly in case of failure.

### CODE REVIEW

**Comment by arichiardi** [comment]
Finally I got around to do this :smile:

**Comment by allentiak** [comment]
Sorry for the late reply, @arichiardi.
Thanks for your hard work!
I'll check it.

**Comment by allentiak** [comment]
Thanks! Sorry for the delay.

**Comment by allentiak** [comment]
Closes #238

**Pull request merged**
