### PR TITLE
Add task for compiling less files

### PR DESCRIPTION
**Pull request by bhagany**
I was inspired to do this by a conversation with @arichiardi on slack - it's pretty basic, but I think it fits well with Perun as it stands.

### CODE REVIEW

**Review by podviaznikov — APPROVED** [review]

**Comment by podviaznikov** [comment]
Code looks good to me

**Comment by arichiardi** [comment]
Thanks for the nice gift @bhagany :christmas_tree: 

I am trying this, while it is working fine, I don't feel totally at easy with the following: in order to build now, I have basically to install `lessc` externally (not from `boot` I mean) - the build is not self-contained anymore.

So I still think that `boot-npm` provides value here, sorry if I am a bit picky :smile: just sharing some concern :wink:

**Comment by arichiardi** [comment]
Actually there is a little problem, when I use it this way:

```
(perun/lessc :filterer #(-> % :filename (= "blog.less")))
```

I get:

```
$ tree target/public/

└── public
    └── css
        └── blog.css
```

Probably some issue with the output dirs, which I think I had to take into consideration in my task as well.

**Comment by bhagany** [comment]
> I am trying this, while it is working fine, I don't feel totally at easy with the following: in order to build now, I have basically to install lessc externally (not from boot I mean) - the build is not self-contained anymore.

Yes, this is what I meant in our conversation on slack, here:
image

As for your output dir problem, I think Perun's pattern is just different from your expectation.  If your input file is at `public/css/blog.less`, and your `:out-dir` is `public` (which is the default), then what you're seeing is expected.  Perun takes the input path, applies any transformations like rendering, and then appends that to `:out-dir`.

I think if you want things in your input `public` dir to be in `target/public`, you can set `:out-dir` to `""`

**Comment by arichiardi** [comment]
ok got it, so that probably is solved just by moving the folder out of `public`. It makes sense. Thanks I did not think about it ;)

**Comment by bhagany** [comment]
... likewise, I'm rather inclined to say that this change isn't in line with how Perun works elsewhere https://github.com/hashobject/perun/pull/200/files

**Comment by bhagany** [comment]
Ah, yes, moving your files out of `public` in the input would work as well

**Comment by arichiardi** [comment]
Uhm, but that did not make too much sense. Why is `public` showing up after `out-dir`? The problem is better explained here https://github.com/hashobject/perun/issues/199

**Comment by bhagany** [comment]
Yes, it’s another instance of the same misunderstanding, possibly complicated by `:dir-root`. To explain, this:
```
(perun/render :renderer 'com.andrearichiardi.blog.post/render
              :out-dir "blog/posts/")
```
should take an input file like `public/foo.html` and put the output at `blog/posts/public/foo.html` because of the appending behavior explained earlier. The permalink is just a function of that path, and `:dir-root` only comes into play if it exists at the beginning of the file’s path, in which case it gets removed. 

That change to `render` breaks the appending behavior that every other Perun task with file output still has.

**Comment by arichiardi** [comment]
Uhm, we can of course revert the commit, if I can come up with an alternative solution :smile:

**Comment by bhagany** [comment]
ah, yeah, without that commit the "Perun way" would be the same as with the less file - move the input file out of `public`

**Comment by arichiardi** [comment]
ok, I am fine without the commit, I can always change my stuff ... betten than breaking everything for everybody :smile:

**Comment by bhagany** [comment]
@podviaznikov any opinions on this?

**Comment by podviaznikov** [comment]
First of all https://github.com/degree9/boot-npm looks impressive. Can't believe how many projects come up everytime in boot ecosystem. Does it require you to have node/npm installed?
If it requires node/npm installation - this seems to me similar to us requires less to be installed.

I guess I would go with this implementation.
The beauty of perun is that user is not forced to use this plugin but use your own version of it (with different implementation).

Core plugins seems like a bit opinionated batteries (we can change our opinions later too) - that everyone is free to replace/ignore.

Does it make sense to you @bhagany and @arichiardi? Just my opinion. Also, the cool thing about plugin - implementation can be changed in the future and task would work. So I'd rather merge this one

**Comment by arichiardi** [comment]
I think you are right @podviaznikov, still something external needs to be installed.

**Comment by bhagany** [comment]
Yes, that makes sense to me @podviaznikov

**Comment by bhagany** [comment]
It just occurred to me that you could probably do something like this to install less for you:

```clj
(def my-lessc
    (comp (degree9.boot-npm/npm :install "less@latest" :global true)
          (io.perun/lessc)))
```

**Comment by bhagany** [comment]
hmmmmmmmm hm hm hm - I am reconsidering my position on the `:out-dir` problem @arichiardi ... I found some old code that never got merged that addresses a similar issue, but for all of Perun instead of just `content-paths`.  I'll follow up in a separate PR.

**Comment by arichiardi** [comment]
About lessc, I am using the [boot-css](https://github.com/degree9/boot-css/blob/master/src/degree9/boot_css.clj) task at the moment cause it basically does everything for you. It's been simplified considerably.

**Comment by bhagany** [comment]
ah, yes, but Perun's will do fileset diffing, and skip less compilation if possible :)

**Comment by arichiardi** [comment]
Oh, right, that's nice to have :smile: Big selling point!

**Comment by arichiardi** [comment]
Hi folks, just wondering if this one is going to be merged. I have a new blog waiting for a blog post :smile:

**Comment by bhagany** [comment]
nice! I like to give other people a bit of time to weigh in if they want, but if there's demand, I don't mind merging it :)

**Pull request merged**
