### PR TITLE
use explicit :include-atom and :include-rss flags for inclusion in feeds

### PR DESCRIPTION
**Pull request by bhagany**
Following @MartyGentillon, here: https://github.com/hashobject/perun/pull/109#issuecomment-263157303.  Intent is more clear, and this change or something like it is a prerequisite for fulfilling the goals of #109.

### CODE REVIEW

**Comment by martinklepsch** [comment]
Two questions:
- Can you think of situations where you'd want to render one atom-feed and another rss-feed with different items?
- This somehow couples the `content` task to the implementation of the RSS and Atom tasks as these know about those keys and read from them. Maybe the `default-meta` map should be supplied as an option and thus be extendable to the users needs? (We could still have some sensible defaults ofc)

**Comment by bhagany** [comment]
- No, I just went for maximum flexibility.  I can't even think of a situation where you're using both `atom-feed` and `rss`.  In any case, this implementation is just as coupled as before, it's just that in this case the coupling goes the opposite way.  (in master, `atom-feed` and `rss` know about `markdown`, in this branch, `markdown` knows about `atom-feed` and `rss`)
 - Yes!  I have a pull request planned to modify the meta in exactly the way you describe.  In the meantime, this implementation allows for overriding the default by putting it in the yaml in markdown files, or the original method of changing the `:filterer` on `atom-feed` and `rss`.

**Comment by martinklepsch** [comment]
Ok sounds good to me then 👍 

I'll just go ahead and merge @Deraen @podviaznikov

**Comment by bhagany** [comment]
Great, thanks!

**Comment by podviaznikov** [comment]
This looks good to me. Great change.
We only need to update our Spec file https://github.com/hashobject/perun/blob/master/SPEC.md with those new properties.

**Pull request merged**
