### PR TITLE
images-meta & images-resize tasks

### PR DESCRIPTION
**Pull request by podviaznikov**
According to #66 I created first implementation of `images-meta` task.

Reviews are welcome.

### CODE REVIEW

**Comment by Deraen** [comment]
I think @martinklepsch's suggestion about `contrib` ns makes sense. 
`io.perun.contrib.images-meta` for impl and `io.perun.contrib` for task?

**Comment by Deraen** [comment]
As a general thought, there should probably be good image processing libs for Java so that no executable is needed?
- ImageJ: http://rsbweb.nih.gov/ij/developer/api/ij/io/Opener.html
- Im4Java: http://im4java.sourceforge.net/
  - This is in fact just ImageMagic C lib JNI compiled, packaged to as JAR and with Java interface

**Comment by podviaznikov** [comment]
Agree about `io.perun.contrib` suggestion - will do.

**Comment by podviaznikov** [comment]
@Deraen I'll take a look into Java libs. Your suggestion makes total sense to me

**Comment by Deraen** [comment]
ImageJ looks to be updated regularly: http://mvnrepository.com/artifact/net.imagej/ij
Im4Java looks quite abandoned (or perhaps it's just ready): http://mvnrepository.com/artifact/org.im4java/im4java
JMagic (ImageMagic JNI package) looks quite abandoned also: http://mvnrepository.com/artifact/jmagick/jmagick

**Comment by Deraen** [comment]
Also, a Clojure lib: https://github.com/josephwilk/image-resizer

https://github.com/josephwilk/image-resizer/blob/master/src/image_resizer/util.clj#L9

Looks like to get image dimensions, `java.awt` is enough.

**Comment by podviaznikov** [comment]
@Deraen so I'm not only extracting dimensions, but also base colors from the image. `image-resizer` looks cool and it would be possible to use it for cropping images or resizing but I can't extract colors with it. I assume that can be done with `java.awt`, but need to find good way to do it

**Comment by Deraen** [comment]
http://docs.oracle.com/javase/7/docs/api/java/awt/image/BufferedImage.html#getRGB(int,%20int)

What kind of color data do you want? To get one average color take some number of samples and blend them together. Dominant color needs a bit more calculation, but there are Java examples available: https://github.com/SvenWoltmann/color-thief-java/ (not sure if available in Mvnrepository).

**Comment by podviaznikov** [comment]
@Deraen I was just looking exactly on the same page (https://github.com/SvenWoltmann/color-thief-java/) :smile: . I think it will do what I want for now. Thanks!

**Comment by Deraen** [comment]
Cool stuff!

I can imagine how cool if would look to use image dominant color in the page. It's a shame that usually when writing about code there aren't that many images :D Maybe I'll finally start a food blog so that I can use this feature.

**Comment by podviaznikov** [comment]
Yeah, take a look at http://jack.ventures/ which is generated using https://github.com/Jack000/Expose/.
He extracts colors from the image and then uses one color as image background (while it's loading) and another one as text color. I think [The Grid](https://thegrid.io/) trying to do something a little bit similar.

It's funny that you mentioned food blog :smile:. I help running this [cooking group](http://www.meetup.com/SF-International-People-Authentic-Cuisine/photos/) and want to try to generate site using perun and new plugins similar to http://jack.ventures/.  Will see how it goes

**Comment by podviaznikov** [comment]
@Deraen what to do if library is not in the Maven repo? What are the usual steps to solve this?

**Comment by podviaznikov** [comment]
Added `images-resize` task

**Comment by Deraen** [comment]
When a library is not in Maven repo, you can either find another or package the library yourself to jar and push to clojars or such.

**Comment by podviaznikov** [comment]
Ok, so this now introduces 2 new tasks:
-  `images-dimensions` - adds `width` & `height` to the file metadata
-  `images-resize` - resized images based on the provided `resolutions`

Extracting palette/colors would be done as separate task.

**Comment by podviaznikov** [comment]
I'm going to merge this for now. But you still comment on this PR with suggestions/comments. My changes shouldn't break anythings since those are mostly additions and it should be safe to merge in.

**Pull request merged**
