### PR TITLE
change posts primary title field from :name to :title

### PR DESCRIPTION
**Pull request by martinklepsch**
Brings things more in line with existing static site generators like jekyll.

### CODE REVIEW

**Comment by nicorikken** [comment]
When will this be merged? This could save the Asciidoctor plugin a transformation from :title to :name for the time being 😛

**Comment by podviaznikov** [comment]
This would be a breaking change but makes sense to me. Didn't see it before

**Comment by podviaznikov** [comment]
@Deraen do you have any opinion on this?

**Comment by Deraen** [comment]
Fine by me.

**Pull request merged**
