### PR TITLE
Consolidate examples

### PR DESCRIPTION
**Pull request by allentiak**
WIP = Work In Progress :-)

### CODE REVIEW

**Review by jaidetree — COMMENTED** [review]
Looks good to me, thanks for fixing the examples 👍 Let’s see what @podviaznikov has to say 😄

**Comment by allentiak** [comment]
There are two examples: a blog and an exposé.
The first one works OK.

The second one is incomplete and buggy. As it stands now, it is only dead weight.

I think the best is to simply erase the exposé, leaving only the blog.
There are plenty of real-world, working websites in the main README.md.

What's your opinion, @podviaznikov , @eccentric-j ?

**Review by jaidetree — COMMENTED** [review]
I agree with you, the expose is another example that will require maintenance. Plus if a person follows along the blog example I'm sure they'll get pretty quickly how to use a subset of those features for a simpler expose style site.

**Review by jaidetree — APPROVED** [review]

**Review by podviaznikov — APPROVED** [review]

**Comment by podviaznikov** [comment]
Looks good! Thank you

**Comment by eccentric-j** [comment]
Good work, thanks Allentiak.

**Comment by jaidetree** [comment]
Good work, thanks @allentiak and @podviaznikov!

**Pull request merged**
