### PR TITLE
Add preprocessor option for markdown task

### PR DESCRIPTION
**Pull request by edannenberg**
See #105 for details. Not sure if it would have been better to put `:preprocessor` inside the `:options` map instead.

### CODE REVIEW

**Comment by MartyGentillon** [comment]
Does the preprocessor reload correctly when changed without restarting boot?

(I am noticing the pod pool being used for this in the render task, and wondering if you need something similar.  Alternately, using tools namespace as in https://github.com/hashobject/perun/pull/104)

**Comment by MartyGentillon** [comment]
One other sidenote: overall this feels like the wrong approach, a result of the underlying design flaw in markdown processing (and perhaps the library overall).  Ideally, tasks should be built by composing simpler subtasks.  the markdown task should be defined something like:

``` clojure
(deftask markdown 
  (process-yaml-frontmatter)
  (parse-markdown))
```

or perhaps even:

``` clojure
(deftask markdown
  (slurp-file-contents)
  (process-yaml-frontmatter)
  (parse-markdown))
```

If it were set up this way, then there would be no need for Perun to know about markdown preprocessing.  You could simply add a preprocess-markdown task to a my-markdown task.

A couple other benefits to this approach:

1) The process-yaml-frontmatter functionality could be more easily shared between markdown, ascidoc, and html-fragment tasks.
2) Other transformations of the html output become more tenable.  For instance, someone could add a link checker that makes sure all the links in the website are valid.

The primary design flaw which prevents this is that the add-filedata function overwrites any processing done by any previous tasks.  If it instead only added data for missing files, we would be able to approach the problem this way.

None of this is to say that this pull request should be thrown away.  It's possible that this is a good short term solution for the problem being encountered.  Just that the alternate approach is worthy of consideration.

**Comment by edannenberg** [comment]
> Does the preprocessor reload correctly when changed without restarting boot?

Nope, it's just a quick 90% solution at this point that removes an impediment for me. Will take a look at reloading once I got a bit more time on my hands.

As I'm still fairly new to Perun I'll let others comment on your other points, once some consensus is reached on how this should be implemented I'll update the PR.

**Comment by podviaznikov** [comment]
@MartyGentillon I would love to have possibility to have better `markdown` task myself. I do think it should offer more customization.
E.x. I have personal use case for post-processor part of markdown task.
My case is following:
1) convert markdown to html.
2) add tachyons css classes http://tachyons.io/ to the appropriate HTML tags.

Right now I'm doing it in the following way:

```
(defn transform-html [html]
  (-> html
    (cue/replace "<h2>" "<h2 class=\"f5\">")
    (cue/replace "<h3>" "<h3 class=\"f6\">")
    (cue/replace "<strong>" "<strong class=\"b\">")
    (cue/replace "<em>" "<em class=\"i\">")
    (cue/replace "<a href" "<a class=\"link\" href")
    (cue/replace "<blockquote>" "<blockquote class=\"athelas ml0 mt0 pl4 black-90 bl bw2 b--blue\">")
    ))

(defn transform-file-content [file]
  (let [content (:content file)
        new-content (transform-html content)]
    (assoc file :content new-content)))
```

But it would be probably nice if I can just register post-processor with `markdown` task.

However I'm not sure how that should look like. Maybe it should look exactly like you suggest. Or maybe some other way is possible.

Hard for me to say at this point. Would love to hear input from others.

**Comment by Deraen** [comment]
Customizing markdown (or other tasks) would be much easier if we were to run these steps (or at least the custom functions) in the "core" pod. Then there would no need for pod pools or multiple c.t.n refreshes, single c.t.n refresh in pipeline could reload all loaded namespaces.

This will need some thinking, but perhaps the benefits from pods are not that great with Perun.

**Comment by bhagany** [comment]
The commit that closed this PR (and #105) makes `markdown` a composition of two simpler tasks, as suggested above.  You should be able to make your preprocessor function into a standalone task, and then compose it with the `yaml-metadata` and `markdown*` tasks to achieve the result you need.  If you run into issues that make this difficult, let us know.

**Pull request closed without merging**
