### PR TITLE
Bump boot version to 2.7.X

### PR DESCRIPTION
**Pull request by arichiardi**
Plus a warning fix

### CODE REVIEW

**Comment by jab** [comment]
I'm new to Perun and am interested in using it, but hit the issues this PR fixes and found my way here. Looks like this was submitted on June 25th and hasn't gotten any response yet, so just wanted to see if a maintainer might be able to say whether there is interest in merging this.

I also noticed the README in this branch still says "We use Clojure 1.7.0 and Boot 2.5.0. You should have those versions in order to use perun." Should the README be updated to say Boot 2.7.X along with the rest of these changes?

Thanks 😸

**Comment by nicorikken** [comment]
Why is the `:refer :all` also removed in this PR?

**Comment by arichiardi** [comment]
Uhm, it has been some time. I don't remember now, probably to fix some issue with the new version? I will confirm that.

**Comment by arichiardi** [comment]
This is the reason, a conflict:

```
                                                  Boot.main                    Boot.java:  258
                                                        ...                                   
                                              boot.App.main                     App.java:  491
                                           boot.App.runBoot                     App.java:  399
org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke  ClojureRuntimeShimImpl.java:  150
org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke  ClojureRuntimeShimImpl.java:  159
                                                        ...                                   
                                            boot.main/-main                     main.clj:  216
                                         boot.main/-main/fn                     main.clj:  216
                                   clojure.core/load-string                     core.clj: 3959
                                   clojure.core/load-reader                     core.clj: 3957
                                                        ...                                   
                                   boot.user$eval755.invoke                             :   51
                             boot.user$eval755.invokeStatic                             :   51
                                                        ...                                   
                                       clojure.core/require                     core.clj: 5796 (repeats 2 times)
                                         clojure.core/apply                     core.clj:  648
                                                        ...                                   
                                     clojure.core/load-libs                     core.clj: 5758
                                     clojure.core/load-libs                     core.clj: 5774
                                         clojure.core/apply                     core.clj:  648
                                                        ...                                   
                                      clojure.core/load-lib                     core.clj: 5717
                                      clojure.core/load-lib                     core.clj: 5755
                                         clojure.core/apply                     core.clj:  648
                                                        ...                                   
                                         clojure.core/refer                     core.clj: 4087
                                         clojure.core/refer                     core.clj: 4122
                                                        ...                                   
java.lang.IllegalStateException: trace already refers to: #'boot.util/trace in namespace: boot.user
     clojure.lang.ExceptionInfo: trace already refers to: #'boot.util/trace in namespace: boot.user
```

**Comment by nicorikken** [comment]
Thanks for clearing that up. Perhaps trace can be put to a different namespace to keep up the ergonomics of perun. But either way this PR gets my approval.

**Comment by arichiardi** [comment]
:+1:

**Comment by bhagany** [comment]
Sorry for the delay on this, folks.  I started a new job recently-ish, and it has been kicking my butt.  I'm trying to get back into some open source work though.

Anyway, I'm good with this.  I do like the idea of changing the README to reflect the correct version of Boot - would you mind adding that?  I'll merge once that's in.

**Comment by arichiardi** [comment]
Done, is it what you meant?

**Review by podviaznikov — APPROVED** [review]

**Comment by bhagany** [comment]
Yup! Thanks!

**Pull request merged**
