### PR TITLE
Add links to the example index page

### PR DESCRIPTION
**Pull request by podviaznikov**
Make example project visually testable.

### CODE REVIEW

**Comment by bhagany** [comment]
Very happy to see this!

**Comment by podviaznikov** [comment]
@bhagany you mean link to test code?
I think it would help me to test PRs without cloning your branches locally.

It would be good if you can delete your perun fork and create branches directly in this repo. That way I would get testable link for each of your PRs. And it will help me to merge them much faster:)

I'm also setting up running tests, thanks for writing them!

**Comment by bhagany** [comment]
I was referring specifically to the Runnable integration, but in general, yes I like everything in this PR.

> It would be good if you can delete your perun fork and create branches directly in this repo.

No problem!

**Comment by bhagany** [comment]
If there are any other changes I can make to make life easier for you, let me know.

**Comment by podviaznikov** [comment]
No, that would be it:) Thank you so much. I also want to make your life easier so that your PRs get merged faster. So Runnable integration should help me here.

**Pull request merged**
